{
  "name": "PhonePe Merchant Expansion",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Periods",
        "columns": [
          {
            "name": "Period ID",
            "dataType": "int64",
            "sourceColumn": "Period ID",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none",
            "sortByColumn": "Period ID"
          },
          {
            "name": "Quarter Start",
            "dataType": "dateTime",
            "sourceColumn": "Quarter Start",
            "summarizeBy": "none",
            "formatString": "yyyy-MM-dd"
          }
        ],
        "partitions": [
          {
            "name": "Periods",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/periods.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"Period ID\", Int64.Type}, {\"Quarter\", type text}, {\"Quarter Start\", type date}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "States",
        "columns": [
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "States",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/states.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"State\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Districts",
        "columns": [
          {
            "name": "District Key",
            "dataType": "string",
            "sourceColumn": "District Key",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "District",
            "dataType": "string",
            "sourceColumn": "District",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Districts",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/districts.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"District Key\", type text}, {\"State\", type text}, {\"District\", type text}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Payments",
        "columns": [
          {
            "name": "District Key",
            "dataType": "string",
            "sourceColumn": "District Key",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Period ID",
            "dataType": "int64",
            "sourceColumn": "Period ID",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Transactions",
            "dataType": "int64",
            "sourceColumn": "Transactions",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Value INR",
            "dataType": "double",
            "sourceColumn": "Value INR",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Registered Users",
            "dataType": "int64",
            "sourceColumn": "Registered Users",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Registered Merchants",
            "dataType": "int64",
            "sourceColumn": "Registered Merchants",
            "summarizeBy": "none",
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "Payments",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/payments.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"District Key\", type text}, {\"Period ID\", Int64.Type}, {\"Transactions\", Int64.Type}, {\"Value INR\", type number}, {\"Registered Users\", Int64.Type}, {\"Registered Merchants\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Transaction Volume",
            "expression": "VAR p = MAX(Periods[Period ID]) RETURN CALCULATE(SUM(Payments[Transactions]), KEEPFILTERS(Periods[Period ID] = p))",
            "formatString": "#,0",
            "description": "Transactions in the latest visible quarter; sum across geography."
          },
          {
            "name": "Transaction Value INR",
            "expression": "VAR p = MAX(Periods[Period ID]) RETURN CALCULATE(SUM(Payments[Value INR]), KEEPFILTERS(Periods[Period ID] = p))",
            "formatString": "₹#,0",
            "description": ""
          },
          {
            "name": "Registered User Base",
            "expression": "VAR p = MAX(Periods[Period ID]) RETURN CALCULATE(IF(COUNT(Payments[Registered Users]) = COUNTROWS(Payments), SUM(Payments[Registered Users]), BLANK()), KEEPFILTERS(Periods[Period ID] = p))",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Registered Merchant Base",
            "expression": "VAR p = MAX(Periods[Period ID]) RETURN CALCULATE(IF(COUNT(Payments[Registered Merchants]) = COUNTROWS(Payments), SUM(Payments[Registered Merchants]), BLANK()), KEEPFILTERS(Periods[Period ID] = p))",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Volume Billion",
            "expression": "DIVIDE([Transaction Volume], 1000000000)",
            "formatString": "0.00\" B\"",
            "description": ""
          },
          {
            "name": "Value Trillion INR",
            "expression": "DIVIDE([Transaction Value INR], 1000000000000)",
            "formatString": "\"₹\"0.00\" T\"",
            "description": ""
          },
          {
            "name": "Users Million",
            "expression": "DIVIDE([Registered User Base], 1000000)",
            "formatString": "0.00\" M\"",
            "description": ""
          },
          {
            "name": "Merchants Million",
            "expression": "DIVIDE([Registered Merchant Base], 1000000)",
            "formatString": "0.00\" M\"",
            "description": ""
          },
          {
            "name": "Average Transaction Value",
            "expression": "DIVIDE([Transaction Value INR], [Transaction Volume])",
            "formatString": "₹#,0.00",
            "description": ""
          },
          {
            "name": "Users per Merchant",
            "expression": "DIVIDE([Registered User Base], [Registered Merchant Base])",
            "formatString": "0.0",
            "description": ""
          },
          {
            "name": "Transactions per Merchant",
            "expression": "DIVIDE([Transaction Volume], [Registered Merchant Base])",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Value per Merchant",
            "expression": "DIVIDE([Transaction Value INR], [Registered Merchant Base])",
            "formatString": "₹#,0",
            "description": ""
          },
          {
            "name": "Merchants per 100K Users",
            "expression": "100000 * DIVIDE([Registered Merchant Base], [Registered User Base])",
            "formatString": "0.0",
            "description": ""
          },
          {
            "name": "Transaction QoQ",
            "expression": "VAR p = MAX(Periods[Period ID]) VAR previous = CALCULATE([Transaction Volume], REMOVEFILTERS(Periods), Periods[Period ID] = p - 1) RETURN IF(NOT ISBLANK(previous), DIVIDE([Transaction Volume], previous) - 1)",
            "formatString": "0.0%",
            "description": ""
          },
          {
            "name": "Transaction YoY",
            "expression": "VAR p = MAX(Periods[Period ID]) VAR previous = CALCULATE([Transaction Volume], REMOVEFILTERS(Periods), Periods[Period ID] = p - 4) RETURN IF(NOT ISBLANK(previous), DIVIDE([Transaction Volume], previous) - 1)",
            "formatString": "0.0%",
            "description": ""
          },
          {
            "name": "Merchant QoQ",
            "expression": "VAR p = MAX(Periods[Period ID]) VAR previous = CALCULATE([Registered Merchant Base], REMOVEFILTERS(Periods), Periods[Period ID] = p - 1) RETURN IF(NOT ISBLANK(previous), DIVIDE([Registered Merchant Base], previous) - 1)",
            "formatString": "0.0%",
            "description": ""
          },
          {
            "name": "User QoQ",
            "expression": "VAR p = MAX(Periods[Period ID]) VAR previous = CALCULATE([Registered User Base], REMOVEFILTERS(Periods), Periods[Period ID] = p - 1) RETURN IF(NOT ISBLANK(previous), DIVIDE([Registered User Base], previous) - 1)",
            "formatString": "0.0%",
            "description": ""
          },
          {
            "name": "State Contribution",
            "expression": "DIVIDE([Transaction Volume], CALCULATE([Transaction Volume], REMOVEFILTERS(States), REMOVEFILTERS(Districts)))",
            "formatString": "0.0%",
            "description": ""
          },
          {
            "name": "Retail Volume Billion",
            "expression": "VAR p = MAX(Periods[Period ID]) RETURN CALCULATE(DIVIDE(SUM('State Payments'[Retail Transactions]), 1000000000), KEEPFILTERS(Periods[Period ID] = p))",
            "formatString": "0.00\" B\"",
            "description": ""
          }
        ]
      },
      {
        "name": "State Payments",
        "columns": [
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Period ID",
            "dataType": "int64",
            "sourceColumn": "Period ID",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Retail Transactions",
            "dataType": "int64",
            "sourceColumn": "Retail Transactions",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "State Payments",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/state_payments.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"State\", type text}, {\"Period ID\", Int64.Type}, {\"Retail Transactions\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Opportunities",
        "columns": [
          {
            "name": "District Key",
            "dataType": "string",
            "sourceColumn": "District Key",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Score",
            "dataType": "double",
            "sourceColumn": "Score",
            "summarizeBy": "none"
          },
          {
            "name": "YoY Growth",
            "dataType": "double",
            "sourceColumn": "YoY Growth",
            "summarizeBy": "none"
          },
          {
            "name": "Users per Merchant",
            "dataType": "double",
            "sourceColumn": "Users per Merchant",
            "summarizeBy": "none"
          },
          {
            "name": "Transactions per Merchant",
            "dataType": "double",
            "sourceColumn": "Transactions per Merchant",
            "summarizeBy": "none"
          },
          {
            "name": "Users",
            "dataType": "int64",
            "sourceColumn": "Users",
            "summarizeBy": "none"
          },
          {
            "name": "Merchants",
            "dataType": "int64",
            "sourceColumn": "Merchants",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "National Rank",
            "dataType": "int64",
            "sourceColumn": "National Rank",
            "summarizeBy": "none"
          },
          {
            "name": "Low Penetration Percentile",
            "dataType": "double",
            "sourceColumn": "Low Penetration Percentile",
            "summarizeBy": "none"
          },
          {
            "name": "Growth Percentile",
            "dataType": "double",
            "sourceColumn": "Growth Percentile",
            "summarizeBy": "none"
          },
          {
            "name": "Equal Weight Rank",
            "dataType": "int64",
            "sourceColumn": "Equal Weight Rank",
            "summarizeBy": "none"
          },
          {
            "name": "No Intensity Rank",
            "dataType": "int64",
            "sourceColumn": "No Intensity Rank",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Opportunities",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/opportunities.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"District Key\", type text}, {\"Score\", type number}, {\"YoY Growth\", type number}, {\"Users per Merchant\", type number}, {\"Transactions per Merchant\", type number}, {\"Users\", Int64.Type}, {\"Merchants\", Int64.Type}, {\"Segment\", type text}, {\"National Rank\", Int64.Type}, {\"Low Penetration Percentile\", type number}, {\"Growth Percentile\", type number}, {\"Equal Weight Rank\", Int64.Type}, {\"No Intensity Rank\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Opportunity Score",
            "expression": "IF(HASONEVALUE(Districts[District Key]), MAX(Opportunities[Score]))",
            "formatString": "0.0",
            "description": ""
          },
          {
            "name": "Opportunity YoY",
            "expression": "IF(HASONEVALUE(Districts[District Key]), MAX(Opportunities[YoY Growth]))",
            "formatString": "0.0%",
            "description": ""
          },
          {
            "name": "Opportunity Users per Merchant",
            "expression": "IF(HASONEVALUE(Districts[District Key]), MAX(Opportunities[Users per Merchant]))",
            "formatString": "0.0",
            "description": ""
          },
          {
            "name": "Eligible Districts",
            "expression": "COUNTROWS(Opportunities)",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Expand Districts",
            "expression": "CALCULATE(COUNTROWS(Opportunities), Opportunities[Segment] = \"EXPAND\")",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Defend Districts",
            "expression": "CALCULATE(COUNTROWS(Opportunities), Opportunities[Segment] = \"DEFEND\")",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Develop Districts",
            "expression": "CALCULATE(COUNTROWS(Opportunities), Opportunities[Segment] = \"DEVELOP\")",
            "formatString": "#,0",
            "description": ""
          },
          {
            "name": "Monitor Districts",
            "expression": "CALCULATE(COUNTROWS(Opportunities), Opportunities[Segment] = \"MONITOR\")",
            "formatString": "#,0",
            "description": ""
          }
        ]
      },
      {
        "name": "State Opportunities",
        "columns": [
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "State Rank",
            "dataType": "int64",
            "sourceColumn": "State Rank",
            "summarizeBy": "none"
          },
          {
            "name": "State Score",
            "dataType": "double",
            "sourceColumn": "State Score",
            "summarizeBy": "none"
          },
          {
            "name": "Eligible Districts",
            "dataType": "int64",
            "sourceColumn": "Eligible Districts",
            "summarizeBy": "none"
          },
          {
            "name": "Expand Districts",
            "dataType": "int64",
            "sourceColumn": "Expand Districts",
            "summarizeBy": "none"
          },
          {
            "name": "Users",
            "dataType": "int64",
            "sourceColumn": "Users",
            "summarizeBy": "none"
          },
          {
            "name": "Merchants",
            "dataType": "int64",
            "sourceColumn": "Merchants",
            "summarizeBy": "none"
          },
          {
            "name": "Transactions",
            "dataType": "int64",
            "sourceColumn": "Transactions",
            "summarizeBy": "none"
          },
          {
            "name": "Merchants per 100K Users",
            "dataType": "double",
            "sourceColumn": "Merchants per 100K Users",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "State Opportunities",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/state_opportunities.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"State\", type text}, {\"State Rank\", Int64.Type}, {\"State Score\", type number}, {\"Eligible Districts\", Int64.Type}, {\"Expand Districts\", Int64.Type}, {\"Users\", Int64.Type}, {\"Merchants\", Int64.Type}, {\"Transactions\", Int64.Type}, {\"Merchants per 100K Users\", type number}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "State Opportunity Score",
            "expression": "MAX('State Opportunities'[State Score])",
            "formatString": "0.0",
            "description": ""
          }
        ]
      },
      {
        "name": "Recommendations",
        "columns": [
          {
            "name": "District Key",
            "dataType": "string",
            "sourceColumn": "District Key",
            "summarizeBy": "none",
            "isHidden": true
          },
          {
            "name": "Priority",
            "dataType": "int64",
            "sourceColumn": "Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Score",
            "dataType": "double",
            "sourceColumn": "Score",
            "summarizeBy": "none"
          },
          {
            "name": "YoY Growth",
            "dataType": "double",
            "sourceColumn": "YoY Growth",
            "summarizeBy": "none"
          },
          {
            "name": "Users per Merchant",
            "dataType": "double",
            "sourceColumn": "Users per Merchant",
            "summarizeBy": "none"
          },
          {
            "name": "Merchants",
            "dataType": "int64",
            "sourceColumn": "Merchants",
            "summarizeBy": "none"
          },
          {
            "name": "Segment",
            "dataType": "string",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Positive YoY Quarters",
            "dataType": "int64",
            "sourceColumn": "Positive YoY Quarters",
            "summarizeBy": "none"
          },
          {
            "name": "Action",
            "dataType": "string",
            "sourceColumn": "Action",
            "summarizeBy": "none"
          },
          {
            "name": "Alternative Rank",
            "dataType": "int64",
            "sourceColumn": "Alternative Rank",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Recommendations",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(DataFolder & \"/recommendations.csv\"), [Delimiter=\",\", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),",
                "    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    Typed = Table.TransformColumnTypes(Headers, {{\"District Key\", type text}, {\"Priority\", Int64.Type}, {\"Score\", type number}, {\"YoY Growth\", type number}, {\"Users per Merchant\", type number}, {\"Merchants\", Int64.Type}, {\"Segment\", type text}, {\"Positive YoY Quarters\", Int64.Type}, {\"Action\", type text}, {\"Alternative Rank\", Int64.Type}}, \"en-US\")",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Shortlist Score",
            "expression": "MAX(Recommendations[Score])",
            "formatString": "0.0",
            "description": ""
          },
          {
            "name": "Shortlist YoY",
            "expression": "MAX(Recommendations[YoY Growth])",
            "formatString": "0.0%",
            "description": ""
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "feee21b0-624c-5a12-ac2d-b8e46ab264ba",
        "fromTable": "Payments",
        "fromColumn": "Period ID",
        "toTable": "Periods",
        "toColumn": "Period ID",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "26ec6bdb-62f0-5ba5-ab75-7313c0577f3f",
        "fromTable": "Payments",
        "fromColumn": "District Key",
        "toTable": "Districts",
        "toColumn": "District Key",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "78f8eeb7-14f4-5cf1-a743-2d19c176867a",
        "fromTable": "Districts",
        "fromColumn": "State",
        "toTable": "States",
        "toColumn": "State",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "986f6252-d0c7-59fe-8a8a-d125018728aa",
        "fromTable": "State Payments",
        "fromColumn": "State",
        "toTable": "States",
        "toColumn": "State",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "309f8c3a-d588-55e6-a393-bbbfe68953bf",
        "fromTable": "State Payments",
        "fromColumn": "Period ID",
        "toTable": "Periods",
        "toColumn": "Period ID",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "6b8bd784-7233-5f91-aa8f-61a83f9f452d",
        "fromTable": "Opportunities",
        "fromColumn": "District Key",
        "toTable": "Districts",
        "toColumn": "District Key",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "ed845ac6-296b-5234-bbd2-f791dca12c0a",
        "fromTable": "State Opportunities",
        "fromColumn": "State",
        "toTable": "States",
        "toColumn": "State",
        "crossFilteringBehavior": "oneDirection"
      },
      {
        "name": "8c88562c-9ba4-5c7c-88bf-d355daa8fced",
        "fromTable": "Recommendations",
        "fromColumn": "District Key",
        "toTable": "Districts",
        "toColumn": "District Key",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DataFolder",
        "kind": "m",
        "expression": "\"D:/PhonePe-Merchant-Expansion-2026/powerbi/data\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
      }
    ]
  }
}